import {FormSchema} from "@/types/form";

export const dataSource: FormSchema = {
    title: 'Форма договор',
    controls: [
        {
            id: '5927943491',
            control: 'FORM',
            caption: 'Открыть договор',
            parentID: '',
            tabIndex: 0,
            position: 0,
        },
        {
            id: '5927943492',
            control: 'TEXT',
            caption: 'Кредит',
            parentID: '5927943491',
            tabIndex: 1,
            position: 1,
            type: 'text',
            required: true
        },
        {
            id: '5927943495',
            control: 'LABEL',
            caption: 'Вид кредита',
            parentID: '5927943491',
            tabIndex: -1,
            position: 2,
            type: 'label',
        },
        {
            id: '5927943496',
            control: 'TEXT',
            caption: 'Финансовый продукт',
            parentID: '5927943491',
            tabIndex: 2,
            position: 3,
            required: true,
            type: 'text',
        },
        {
            id: '5927943750001',
            control: 'RADIO',
            caption: 'Тип кредита',
            parentID: '5927943491',
            tabIndex: 3,
            position: 4,
            required: true,
            options: [
                { label: 'Потребительский', value: 'consumer', selected: true },
                { label: 'Ипотечный', value: 'mortgage' },
            ],
        },
        {
            id: '5927943750002',
            control: 'SELECT',
            caption: 'Сумма кредита',
            parentID: '5927943491',
            tabIndex: 4,
            position: 5,
            type: 'select',
            required: true,
            dependencies: [
                {
                    fieldId: '5927943750001',
                    value: 'mortgage',
                    action: 'show',
                },
            ],
            options: [
                { label: '1 000', value: 1 },
                { label: '2 000', value: 2 },
                { label: '3 000', value: 3 },
                { label: '4 000', value: 4 },
            ],
        },
        {
            id: '5927943750004',
            control: 'TEXT',
            caption: 'Имя заемщика',
            parentID: '5927943491',
            tabIndex: 6,
            position: 7,
            required: true,
            type: 'text',
        },
        {
            id: '5927943750005',
            control: 'TEXT',
            caption: 'Фамилия заемщика',
            parentID: '5927943491',
            tabIndex: 7,
            position: 8,
            required: true,
            type: 'text',
        },
        {
            id: '5927943750006',
            control: 'TEXT',
            caption: 'Серия и номер паспорта',
            parentID: '5927943491',
            tabIndex: 8,
            position: 9,
            required: true,
            type: 'text',
        },
        {
            id: '5927943750003',
            control: 'CHECKBOX',
            caption: 'Я согласен с условиями договора',
            parentID: '5927943491',
            tabIndex: 5,
            position: 10,
            required: true,
            type: 'checkbox',
        },
        {
            id: '5927943750007',
            control: 'BUTTON',
            caption: 'Сохранить',
            parentID: '5927943491',
            tabIndex: 9,
            position: 11,
            type: 'button',
            dependencies: [
                {
                    fieldId: '5927943750003',
                    value: true,
                    action: 'disabled',
                },
            ],
        },
        {
            id: '5927943750008',
            control: 'BUTTON_CANCEL',
            caption: 'Отмена',
            parentID: '5927943491',
            tabIndex: 10,
            position: 12,
            type: 'button',
            variant: 'secondary',
        },
    ],
    submitUrl: '/api/submitForm',
};




